[project]
name = "grade-guardian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Devon Jones", email = "devon.jones@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.0",
    "pyyaml>=6.0.0",
]

[project.scripts]
grade-guardian = "grade_guardian:main"

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"
